name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Run tests in Hypernode Docker container
      run: |
        docker run --rm \
          -v $(pwd):/workspace \
          -w /workspace \
          docker.hypernode.com/byteinternet/hypernode-bookworm-docker-php84-mysql80 \
          bash -c "
            apt-get update && apt-get install -y python3-pip python3-venv
            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            python -m pytest tests/ -v
          "
          
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false 